# Generated by Django 3.2.8 on 2021-10-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Positivo', 'Positivo'), ('Daten', 'Daten'), ('Outro', 'Outro')], max_length=50)),
                ('gabinete_tipo', models.CharField(choices=[('Normal', 'Normal'), ('Gabinete Horizontal', 'Gabinete Horizontal')], default='Normal', max_length=100)),
                ('usb_frontal', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('Normal', 'Normal'), ('Notebook', 'Notebook'), ('HD Externo', 'HD Externo')], default='Normal', max_length=50)),
                ('tamanho_gb', models.IntegerField()),
                ('funciona', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('hdmi', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('tamanho', models.CharField(blank=True, max_length=15)),
                ('funciona', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('usb', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('funciona', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.FloatField(blank=True)),
                ('memoria_cache', models.IntegerField(blank=True, default=0)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Processadores',
            },
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('usb', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('funciona', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('hdmi', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('processador_suporte', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=10)),
                ('socket', models.CharField(blank=True, max_length=50)),
                ('funciona', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('descricao', models.TextField(blank=True)),
                ('pl_processador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.processador')),
            ],
            options={
                'verbose_name': 'Placas Mãe',
                'verbose_name_plural': 'Placas Mãe',
            },
        ),
    ]
