# Generated by Django 3.2.8 on 2021-10-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacaDeRede',
        ),
    ]
