# Generated by Django 3.2.8 on 2021-10-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_delete_placaderede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name_plural': 'Monitores'},
        ),
        migrations.AlterModelOptions(
            name='placamae',
            options={'verbose_name': 'Placas Mãe', 'verbose_name_plural': 'Placas Mãe'},
        ),
        migrations.AlterModelOptions(
            name='processador',
            options={'verbose_name_plural': 'Processadores'},
        ),
    ]
