# Generated by Django 3.2.8 on 2021-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_memoriaram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hd',
            name='funciona',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='funciona',
        ),
        migrations.AddField(
            model_name='monitor',
            name='patrimonio',
            field=models.CharField(blank=True, help_text='Número do patrimônio', max_length=50, null=True, verbose_name='Patrimônio'),
        ),
        migrations.AlterField(
            model_name='hd',
            name='tamanho_gb',
            field=models.IntegerField(verbose_name='Tamanho GB'),
        ),
        migrations.AlterField(
            model_name='processador',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=20, verbose_name='modelo'),
        ),
    ]
