# Generated by Django 3.2.8 on 2021-10-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20211022_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoriaRam',
        ),
    ]
