# Generated by Django 3.2.8 on 2021-10-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0019_computador_patrimonio'),
        ('inventario', '0005_gabinete_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabinete',
            name='pai',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filho_gabinete', to='dispositivo.computador'),
        ),
    ]
