# Generated by Django 3.2.8 on 2021-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_gabinete_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
