# Generated by Django 3.2.8 on 2021-10-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_gabinete_criado_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placamae',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='processador',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teclado',
            name='criado_data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
