# Generated by Django 3.2.8 on 2021-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20211031_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='patrimonio',
            field=models.CharField(blank=True, help_text='Número do patrimônio', max_length=50, null=True, verbose_name='Patrimônio'),
        ),
    ]
