# Generated by Django 3.2.8 on 2021-10-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(choices=[('Prefeitura Municipal De Arapoti', 'Prefeitura Municipal de Arapoti'), ('Col. Clotário Portual', 'Colégio Clortário Portugal'), ('Col. Telemaco Carneiro', 'Colégio Telemaco Carneiro'), ('Col. Dona Zizi', 'Colégio Dona Zizi'), ('UBS Jardim Aratinga', 'UBS Jardim Aratinga'), ('UBS Jardim Ceres', 'UBS Jardim Ceres'), ('UBS Vila Romana', 'UBS Vila Romana'), ('CREAS', 'CREAS'), ('CREAS', 'CREAS - Centro de Referência Especializado em Assistência Social')], max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('singla_departamento', models.CharField(blank=True, max_length=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('controle_acesso', models.CharField(choices=[('Pessimista', 'Pessimista'), ('Otimista', 'Otimista')], default='Pessimista', help_text='Controle de acesso a sites rede. Pessimista: Controle rígido; Otimista: Pouco controle.', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('departamento', models.ManyToManyField(to='departamento.Departamento')),
            ],
        ),
    ]
