# Generated by Django 3.2.8 on 2021-10-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(choices=[('Prefeitura Arapoti', 'Prefeitura Municipal de Arapoti'), ('Col. Clotário', 'Colégio Clortário Portugal'), ('Col. Tel.Carneiro', 'Colégio Telemaco Carneiro'), ('Col. D.Zizi', 'Colégio Dona Zizi'), ('UBS Jd.Aratinga', 'UBS Jardim Aratinga'), ('UBS Jd.Ceres', 'UBS Jardim Ceres'), ('UBS Vila Romana', 'UBS Vila Romana'), ('CRAS', 'CRAS'), ('CREAS', 'CREAS - Centro de Referência Especializado em Assistência Social')], max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('singla_departamento', models.CharField(blank=True, max_length=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('usuario_pc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário PC')),
                ('senha_pc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha PC')),
                ('controle_acesso', models.CharField(choices=[('Pessimista', 'Pessimista'), ('Otimista', 'Otimista')], default='Pessimista', help_text='Controle de acesso a sites rede. Pessimista: Controle rígido; Otimista: Pouco controle.', max_length=20, verbose_name='Acesso Proxy')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(default='Prefeitura Municipal De Arapoti', on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
