# Generated by Django 3.2.8 on 2021-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20211021_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='singla_departamento',
            field=models.CharField(blank=True, default='-', max_length=5, null=True),
        ),
    ]
