# Generated by Django 3.2.8 on 2021-10-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20211018_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(default='Prefeitura Municipal De Arapoti', on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
    ]
