# Generated by Django 3.2.8 on 2021-10-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_funcionario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha_pc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha PC'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario_pc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário PC'),
        ),
    ]
