# Generated by Django 3.2.8 on 2021-10-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_auto_20211018_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='controle_acesso',
            field=models.CharField(choices=[('Pessimista', 'Pessimista'), ('Otimista', 'Otimista')], default='Pessimista', help_text='Controle de acesso a sites rede. Pessimista: Controle rígido; Otimista: Pouco controle.', max_length=20, verbose_name='Acesso Proxy'),
        ),
    ]
