# Generated by Django 3.2.8 on 2021-10-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0006_alter_funcionario_controle_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='predio',
            field=models.CharField(choices=[('Prefeitura Arapoti', 'Prefeitura Municipal de Arapoti'), ('Col. Clotário', 'Colégio Clortário Portugal'), ('Col. Tel.Carneiro', 'Colégio Telemaco Carneiro'), ('Col. D.Zizi', 'Colégio Dona Zizi'), ('UBS Jd.Aratinga', 'UBS Jardim Aratinga'), ('UBS Jd.Ceres', 'UBS Jardim Ceres'), ('UBS Vila Romana', 'UBS Vila Romana'), ('CRAS', 'CRAS'), ('CREAS', 'CREAS - Centro de Referência Especializado em Assistência Social')], max_length=255),
        ),
    ]
