# Generated by Django 3.2.8 on 2021-10-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0003_alter_funcionario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(choices=[('TP-LINK', 'TP-Link'), ('D-Link', 'D-Link'), ('Huawei', 'Huawei'), ('Outro', 'Outro')], max_length=50)),
                ('multimodo', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', help_text='Multimodo: Frequência 2.4Ghz e 5Ghz.', max_length=1)),
                ('descricao', models.TextField(blank=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
