# Generated by Django 3.2.8 on 2021-10-20 01:19

from django.db import migrations, models
import django.db.models.deletion
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('departamento', '0001_initial'),
        ('inventario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='0', max_length=100, verbose_name='Modelo')),
                ('tipo_toner', models.CharField(choices=[('Modelo 01', 'Modelo 01'), ('Modelo 02', 'Modelo 02'), ('Modelo 03', 'Modelo 03')], default=('Modelo 01', 'Modelo 01'), max_length=100, verbose_name='Toner')),
                ('sala', models.IntegerField(blank=True, help_text='Número de refência ao local onde a impressora está.', null=True, verbose_name='Número Sala')),
                ('usando_ip', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Está conectada pela rede;usando um ip.', verbose_name='Usando IP')),
                ('pertence_gestpar', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Impressora alugada', verbose_name='Impressora Gestpar')),
                ('gestpar_matricula', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Roteador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(help_text='Nome visivel da rede.', max_length=100, verbose_name='SSID')),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(choices=[('TP-LINK', 'TP-Link'), ('D-Link', 'D-Link'), ('Huawei', 'Huawei'), ('Outro', 'Outro')], max_length=50)),
                ('multimodo', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', help_text='Multimodo: Frequência 2.4Ghz e 5Ghz.', max_length=1)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
            options={
                'verbose_name_plural': 'Roteadores',
            },
        ),
        migrations.CreateModel(
            name='EnderecoMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, integer=True, null=True, unique=True)),
                ('parent_object_id', models.PositiveIntegerField()),
                ('parent_content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac_parente', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Endereço IP')),
                ('parente_objeto_id', models.PositiveIntegerField()),
                ('parente_conteudo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_parente', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_op', models.CharField(blank=True, choices=[('Win7', 'Windows 7'), ('Win8', 'Windows 8'), ('Win10', 'Windows 10'), ('Ubuntu', 'Ubuntu'), ('WinServer', 'Windows Server')], max_length=10, verbose_name='Sistema Operacional')),
                ('sala', models.IntegerField(blank=True, help_text='Número de referência a sala onde ficará o computador')),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento ao qual o computador pertence.', null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.departamento')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Funcionário que utilizará o computador.', null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.funcionario')),
                ('gabinete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.gabinete')),
                ('hd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.hd')),
                ('monitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.monitor')),
                ('mouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.mouse')),
                ('placa_mae', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.placamae', verbose_name='Placa Mãe')),
                ('processador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.processador')),
                ('teclado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.teclado')),
            ],
        ),
    ]
