# Generated by Django 3.2.8 on 2021-10-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='sala',
            field=models.IntegerField(blank=True, help_text='Número de referência a sala onde ficará o computador', null=True),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
