# Generated by Django 3.2.8 on 2021-10-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(default='0', max_length=100, verbose_name='Modelo Impressora'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='usb',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Está conectada utilizando a porta USB.', verbose_name='Usando USB'),
        ),
    ]
