# Generated by Django 3.2.8 on 2021-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0002_auto_20211020_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='anydesk',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='AnyDesk'),
        ),
    ]
