# Generated by Django 3.2.8 on 2021-10-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0002_auto_20211019_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roteador',
            options={'verbose_name_plural': 'Roteadores'},
        ),
        migrations.RemoveField(
            model_name='impressora',
            name='usb',
        ),
        migrations.AddField(
            model_name='impressora',
            name='pertence_gestpar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Impressora alugada', verbose_name='Impressora Gestpar'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='sala',
            field=models.IntegerField(blank=True, help_text='Número de refência ao local onde a impressora está.', null=True, verbose_name='Número Sala'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='tipo_toner',
            field=models.CharField(choices=[('Modelo 01', 'Modelo 01'), ('Modelo 02', 'Modelo 02'), ('Modelo 03', 'Modelo 03')], default=('Modelo 01', 'Modelo 01'), max_length=100, verbose_name='Toner'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='usando_ip',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Está conectada pela rede;usando um ip.', verbose_name='Usando IP'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(default='0', max_length=100, verbose_name='Modelo'),
        ),
    ]
