# Generated by Django 3.2.8 on 2021-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0003_computador_anydesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Impressora'),
        ),
    ]
