# Generated by Django 3.2.8 on 2021-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0004_impressora_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='local',
            field=models.CharField(choices=[('Sala', 'Sala'), ('Corredor', 'Corredor')], default='Corredor', max_length=10, verbose_name='Local Impressora'),
        ),
    ]
