# Generated by Django 3.2.8 on 2021-10-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0006_alter_funcionario_controle_acesso'),
        ('inventario', '0003_auto_20211019_2132'),
        ('dispositivo', '0004_impressora_gestpar_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='gestpar_matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_op', models.CharField(blank=True, choices=[('Win7', 'Windows 7'), ('Win8', 'Windows 8'), ('Win10', 'Windows 10'), ('Ubuntu', 'Ubuntu'), ('WinServer', 'Windows Server')], max_length=10, verbose_name='Sistema Operacional')),
                ('sala', models.IntegerField(blank=True, help_text='Número de referência a sala onde ficará o computador')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.departamento')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.funcionario')),
                ('gabinete', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.gabinete')),
                ('hd', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.hd')),
                ('monitor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.monitor')),
                ('placa_mae', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.placamae')),
                ('processador', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.processador')),
                ('teclado', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.teclado')),
            ],
        ),
    ]
