# Generated by Django 3.2.8 on 2021-10-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20211019_2132'),
        ('dispositivo', '0005_auto_20211019_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='gabinete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.gabinete'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='hd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.hd'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='monitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.monitor'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_mae',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.placamae'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.processador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='teclado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.teclado'),
        ),
    ]
