# Generated by Django 3.2.8 on 2021-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0005_impressora_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='patrimonio',
            field=models.CharField(blank=True, help_text='Número do patrimônio', max_length=50, null=True, verbose_name='Patrimônio Número'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='local',
            field=models.CharField(choices=[('Sala', 'Sala'), ('Corredor', 'Corredor')], default='Sala', max_length=10, verbose_name='Local Impressora'),
        ),
    ]
