# Generated by Django 3.2.8 on 2021-10-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20211019_2132'),
        ('departamento', '0007_alter_departamento_predio'),
        ('dispositivo', '0007_auto_20211019_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento ao qual o computador pertence.', null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='funcionario',
            field=models.ForeignKey(blank=True, help_text='Funcionário que utilizará o computador.', null=True, on_delete=django.db.models.deletion.PROTECT, to='departamento.funcionario'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='gabinete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.gabinete'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='hd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.hd'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='monitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.monitor'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='mouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.mouse'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_mae',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.placamae', verbose_name='Placa Mãe'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.processador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='teclado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.teclado'),
        ),
    ]
