# Generated by Django 3.2.8 on 2021-10-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0007_alter_impressora_patrimonio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecomac',
            old_name='parent_content_type',
            new_name='content_type',
        ),
    ]
