# Generated by Django 3.2.8 on 2021-10-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0008_rename_parent_content_type_enderecomac_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecoip',
            old_name='parente_conteudo_tipo',
            new_name='content_type',
        ),
    ]
