# Generated by Django 3.2.8 on 2021-10-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0010_rename_parente_objeto_id_enderecoip_parent_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computador',
            options={'verbose_name': 'Computador', 'verbose_name_plural': 'Computadores'},
        ),
    ]
