# Generated by Django 3.2.8 on 2021-10-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_memoriaram'),
        ('dispositivo', '0011_alter_computador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='memoria_ram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.memoriaram'),
        ),
    ]
