# Generated by Django 3.2.8 on 2021-10-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_memoriaram'),
        ('dispositivo', '0012_computador_memoria_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.memoriaram', unique=True),
        ),
    ]
