# Generated by Django 3.2.8 on 2021-10-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0013_alter_computador_memoria_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='memoria_ram',
        ),
    ]
