# Generated by Django 3.2.8 on 2021-10-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0014_remove_computador_memoria_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='anydesk',
            field=models.CharField(max_length=120, null=True, verbose_name='AnyDesk'),
        ),
    ]
