# Generated by Django 3.2.8 on 2021-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0015_alter_computador_anydesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='anydesk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='AnyDesk'),
        ),
    ]
