# Generated by Django 3.2.8 on 2021-10-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0016_alter_computador_anydesk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], default='DDR4', max_length=5)),
                ('frequencia', models.FloatField(blank=True, null=True, verbose_name='Frequência')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('computador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoria', to='dispositivo.computador')),
            ],
            options={
                'verbose_name': 'Memória RAM',
                'verbose_name_plural': 'Memórias RAM',
            },
        ),
    ]
