# Generated by Django 3.2.8 on 2021-10-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0017_memoriaram'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='nome_rede',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nome na Rede'),
        ),
    ]
