# Generated by Django 3.2.8 on 2021-10-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_gabinete_pai'),
        ('dispositivo', '0019_computador_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='gabinete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.gabinete'),
        ),
    ]
