# Generated by Django 3.2.8 on 2021-10-30 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_gabinete_pai'),
        ('dispositivo', '0020_alter_computador_gabinete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='hd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.hd'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.monitor'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='mouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.mouse'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='placa_mae',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.placamae', verbose_name='Placa Mãe'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.processador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='teclado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computador', to='inventario.teclado'),
        ),
    ]
