# Generated by Django 3.2.8 on 2021-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_gabinete_pai'),
        ('dispositivo', '0021_auto_20211030_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='monitor',
        ),
        migrations.AddField(
            model_name='computador',
            name='monitor',
            field=models.ManyToManyField(related_name='computador', to='inventario.Monitor'),
        ),
    ]
