# Generated by Django 3.2.8 on 2021-10-31 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_gabinete_pai'),
        ('dispositivo', '0022_auto_20211030_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='monitor',
        ),
        migrations.AddField(
            model_name='computador',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computador', to='inventario.monitor'),
        ),
    ]
