# Generated by Django 3.2.8 on 2021-10-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20211031_1806'),
        ('dispositivo', '0024_auto_20211030_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='monitor',
            field=models.ManyToManyField(blank=True, related_name='computador', to='inventario.Monitor'),
        ),
    ]
