# Generated by Django 3.2.8 on 2021-11-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0025_alter_computador_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='patrimonio',
        ),
    ]
